### ISSUE TITLE
Question: I know I can use this tool at the website but is it possible to use it as an application.

### ISSUE THREAD

**Issue by freefreeno** [jimniels/sassme#5]
I would like to have this as an app in KDE so if this is possible please feel me in. Even if the output was in a terminal window that would be cool. I just don't want to have to open a browser every time I want to use it. I love the tool by the way and it has helped me in so many ways it is pitiful. Thanks so much for making this tool available to some of us less savy people.

**Comment by jimniels** [comment]
There are probably a couple ways you could go about this, but having never built native applications, idk how you could do it natively.

You probably could turn it into a command line app for use in the terminal, but I'm not sure what that interface looks like. Like how do you use a "slider" input via the terminal? You'd have to figure out that interface. 

The math that does the color conversion is in this codebase. If you want to convert that to a native app elsewhere, that's probably a helpful place to get started. But drawing a GUI for a native app and writing code for it, I can't help you there.

**Comment by freefreeno** [comment]
Ok thanks. I build themes and use this tool all the time and it would be great to be able to use it in the terminal like you say as a command line app. Thanks.
