### ISSUE TITLE
Not really an issue , more a question and a suggestion

### ISSUE THREAD

**Issue by freefreeno** [jimniels/sassme#6]
I see a person suggesting a dark or light background but then it gets kinda more complicated than I think you would like the site to be. I suggest a simple slider for dark background or light. Something very similar to this page has or something very simple to do this but with maybe a little darker color though.

![Screenshot_20191129_214332](https://user-images.githubusercontent.com/41884680/69895212-8cfc8880-12f1-11ea-836e-6303333864a7.png)

![Screenshot_20191129_214351](https://user-images.githubusercontent.com/41884680/69895213-8cfc8880-12f1-11ea-857d-ee7c0a455dfa.png)
 
I want to say thank you also. I have a question now. Like this color here #292f34. The tool says nine shades lighter is #3D464E but I have a friend that uses a tool in some application on Mac OS and he says the shade should be #3e474e so my question is there a reason and which one is correct. I use the tool for my UI design in Linux and it helps me tremendously. Many thanks. I think a good dark background would be #282828 or #303030

**Comment by jimniels** [comment]
> I see a person suggesting a dark or light background

Supporting dark mode makes a lot of sense, especially now that we have support for this at the OS-level in major operating systems. I'd love to work on it, but don't have time right now. PRs are welcome 😄 

> Like this color here #292f34. The tool says nine shades lighter is #3D464E but I have a friend that uses a tool in some application on Mac OS and he says the shade should be #3e474e

I'm not sure what tool your friend is using. The color math in the SassMe app appears to be correct. If you cross reference it with a tool that actually compiles Sass, you should see the same result.

For example, here's the color you provided and the associated `lighten` function

![Screen Shot 2019-12-03 at 2 28 58 PM](https://user-images.githubusercontent.com/1316441/70091559-9c255400-15d9-11ea-82c8-f3e4329ce1e2.png)

If you take that Sass function and plop it into Sass, you should see the same output. Here’s an example from [the online Sass compiler Sassmeister](https://www.sassmeister.com/)

![Screen Shot 2019-12-03 at 2 29 04 PM](https://user-images.githubusercontent.com/1316441/70091607-b7905f00-15d9-11ea-9ffa-868fee250514.png)
